Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# Task 1: Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):")
print(empty_array)

# Task 2: Initialize an all ones array with size 4X2
ones_array = np.ones((4, 2))
print("\nAll Ones Array (4x2):")
print(ones_array)

# Task 3: Return a new array of given shape and type, filled with a specified fill value
fill_value_array = np.full((3, 3), 1)  # Example shape (3,3) and fill value 7
print("\nArray filled with 1 (3x3):")
print(fill_value_array)

# Task 4: Return a new array of zeros with same shape and type as a given array
example_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(example_array)
print("\nZeros Array with Same Shape as example_array:")
print(zeros_like_array)

# Task 5: Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(example_array)
print("\nOnes Array with Same Shape as example_array:")
print(ones_like_array)

# Task 6: Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array from List:")
print(numpy_array)


Empty Array (2x2):
[[4.79741119e-310 0.00000000e+000]
 [1.65731948e-287 6.85970285e-310]]

All Ones Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 1 (3x3):
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Zeros Array with Same Shape as example_array:
[[0 0]
 [0 0]]

Ones Array with Same Shape as example_array:
[[1 1]
 [1 1]]

Converted NumPy Array from List:
[1 2 3 4]


Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

#task-1
array_range = np.arange(10, 50)
print("Array with value from 10-49: ")
print(array_range)

#task-2
matrix_3x3 = np.arange(9).reshape((3,3))
print("\n Matrix with value from 3-8: ")
print(matrix_3x3)

#task-3
identity_matrix = np.eye(3)     #it will make a matrix of three columns and rows
print("\n 3x3 indentity matrix: ")
print(identity_matrix)

#task-4
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n random array of size 30: ", random_array)
print("\n mean: ", mean_value)

#task-5
random_10x10 = np.random.random((10,10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n Random value: ", random_10x10)
print("\n max value: ", max_value)
print("\n min value: ", min_value)

#task-6
zero_array = np.zeros(10)
zero_array[4] = 4
print("\n Zero array with fifth element replaced: ", zero_array)

#task-7
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
print("\n Reversed_arr: ", reversed_arr)


#task-8
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on border and 0 inside: ")
print(border_array)

#task-9
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1  # Fill odd rows
checkerboard[::2, 1::2] = 1  # Fill even rows
print("\n8x8 Checkerboard Pattern:")
print(checkerboard)



Array with value from 10-49: 
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

 Matrix with value from 3-8: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

 3x3 indentity matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 random array of size 30:  [0.91841749 0.23508173 0.6635051  0.65873148 0.47647743 0.38019345
 0.8705385  0.56622089 0.5202214  0.40779118 0.36915377 0.98555094
 0.40000193 0.9997877  0.36893701 0.96295557 0.99154377 0.02791568
 0.40700913 0.25716457 0.34215498 0.50970717 0.30623024 0.84131717
 0.65978365 0.29341423 0.78196378 0.3320377  0.56648449 0.407933  ]

 mean:  0.5502741715220453

 Random value:  [[0.16528215 0.01059727 0.46146873 0.83894173 0.46542721 0.87835518
  0.60195186 0.08746133 0.16171026 0.35687887]
 [0.75351309 0.92341757 0.30963047 0.38376276 0.96323985 0.07068158
  0.82292845 0.23544312 0.87789251 0.57127112]
 [0.10049045 0.8362292  0.88671201 0.90667618 0.70600278 0.79923587
  0.01798145 0.2652

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#task-1
array_sum = x+y
print("\n sum of array x & y: ", "\n", array_sum)

#task-2
array_sub = v-w
print("\n subtract of array v&w: ", "\n", array_sub)

#task-3
x_multiplied = x * 2
y_multiplied = y * 3
print("\n x multiplied by 2:", x_multiplied)
print("\n y multiplied by 3:", y_multiplied)


#task-4
x_squared = np.square(x)
y_squared = np.square(y)
print("\nTask 4 - Square of each element of x:")
print(x_squared)
print("\nTask 4 - Square of each element of y:")
print(y_squared)


#task-5
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)
print("\nTask 5 - Dot product of v and w:", dot_v_w)
print("\nTask 5 - Dot product of x and v:", dot_x_v)
print("\nTask 5 - Dot product of x and y:", dot_x_y)

#task-6
concat_x_y_rows = np.concatenate((x, y), axis=0)
print("\nTask 6 - Concatenate x and y along rows:")
print(concat_x_y_rows)


#task-7
v_reshaped = v.reshape(-1, 1)
w_reshaped = w.reshape(-1, 1)
concat_v_w_cols = np.concatenate((v_reshaped, w_reshaped), axis=1)
print("\nTask 6 - Concatenate v and w along columns:")
print(concat_v_w_cols)



try:
    concat_x_v = np.concatenate((x, v), axis=0)
    print("\nTask 7 - Concatenate x and v:")
    print(concat_x_v)
except ValueError as e:
    print("\nTask 7 - Error:", e)


 sum of array x & y:  
 [[ 6  8]
 [10 13]]

 subtract of array v&w:  
 [-2 -2]

 x multiplied by 2: [[ 2  4]
 [ 6 10]]

 y multiplied by 3: [[15 18]
 [21 24]]

Task 4 - Square of each element of x:
[[ 1  4]
 [ 9 25]]

Task 4 - Square of each element of y:
[[25 36]
 [49 64]]

Task 5 - Dot product of v and w: 219

Task 5 - Dot product of x and v: [29 77]

Task 5 - Dot product of x and y: [[19 22]
 [50 58]]

Task 6 - Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Task 6 - Concatenate v and w along columns:
[[ 9 11]
 [10 12]]

Task 7 - Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np

# Given arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Task 1: Prove A.A^-1 = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("Task 1 - Prove A.A^-1 = I:")
print(identity_matrix)

# Task 2: Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nTask 2 - Prove AB ≠ BA:")
print("AB =")
print(AB)
print("BA =")
print(BA)

# Task 3: Prove (AB)^T = B^T A^T
AB_transpose = np.transpose(AB)
B_transpose_A_transpose = np.dot(np.transpose(B), np.transpose(A))
print("\nTask 3 - Prove (AB)^T = B^T A^T:")
print("Transpose of AB:")
print(AB_transpose)
print("B^T A^T:")
print(B_transpose_A_transpose)

# Task 4: Solve the system of linear equations using inverse method
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])  # Coefficient matrix A
B_matrix = np.array([-1, -3, 9])  # Right-hand side matrix B

# Inverse method
A_inv = np.linalg.inv(A_matrix)
X = np.dot(A_inv, B_matrix)

print("\nTask 4 - Solve the system of equations using Inverse Methods:")
print("Solution for x, y, z:")
print(X)


Task 1 - Prove A.A^-1 = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Task 2 - Prove AB ≠ BA:
AB =
[[23 13]
 [51 29]]
BA =
[[36 44]
 [13 16]]

Task 3 - Prove (AB)^T = B^T A^T:
Transpose of AB:
[[23 51]
 [13 29]]
B^T A^T:
[[23 51]
 [13 29]]

Task 4 - Solve the system of equations using Inverse Methods:
Solution for x, y, z:
[ 2.  1. -2.]
